# Generated by Django 2.2.13 on 2021-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Code', models.CharField(max_length=30)),
                ('Emp_Name', models.CharField(max_length=30)),
                ('D_o_Join', models.DateField()),
                ('Salary', models.FloatField()),
            ],
        ),
    ]
